name: Issue Report
description: File an issue with the NHS Wales FHIR Standards and Implementation Team.
title: "[Issue]: "
labels: ["issue", "triage"]
projects: ["NHSWalesFHIR/NHSWales-fhir-profiles-R4"]
assignees:
  - callumsaint
  - DawesCoding
  - RohieKhan
  - SFMusto
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Your call will be logged by the NHS Wales FHIR Standards and Implementation Team and triaged within three working days. Please ensure that you include your full name, a contact email address, and details of your organisation to support follow up.
  - type: input
    id: contact-name
    attributes:
      label: Name
      placeholder: ex. Frederick Bloggs
    validations:
      required: true
  - type: input
    id: contact-address
    attributes:
      label: Contact Details
      placeholder: ex. fred.bloggs@wales.nhs.uk
    validations:
      required: true
  - type: input
    id: contact-organisation
    attributes:
      label: Organisation
      description: If you are reporting in an organisational capacity, what is the name of your organisation?
      placeholder: ex. NHS Wales
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: Which type of issue are you reporting?
      options:
      - Change Request
      - Technical Correction
      - Question
      - Comment
      default: 3
    validations:
      required: true
- type: markdown
    attributes:
      value: |
      | Name  | Description |
      |-------|-------------|
      |Change Request|This is a request for change to the referenced specification that is more significant than a mere technical correction.  If this is being applied during designated formal review periods it suggests an alternative to the proposed change.|
      |Technical Correction|This is a minor change to the specification that is not thought to impact the behaviour of conformant applications e.g. spelling and grammar.|
      |Question|This doesn’t anticipate a change to the specification or the proposal but instead seeks clarification on some aspect of it.|
      |Comment|This is commentary about the specification or proposal that does not fit into any of the other feedback categories e.g. users commenting that they agree with a proposal during designated formal review.|
  - type: input
    id: package-spec
    attributes:
      label: Package Specification
      description: In which package release does the issue occur?
      placeholder: ex. fhir.r4.wales.2.5.0
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      description: Please provide a full description of the issue, including file path(s) and line(s) of code where appropriate.
      placeholder: Description or Comment
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
